// Demonstrate check boxes.
import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

class CBDemo implements ItemListener {
    JLabel jlabSelected;
    JLabel jlabChanged;
    JCheckBox Web;
    JCheckBox Desktop;
    JCheckBox Mobile;

    CBDemo() {
        // Create a new JFrame container.
        JFrame jfrm = new JFrame("Demonstrate Check Boxes");
        // Specify FlowLayout for the layout manager.
        jfrm.setLayout(new FlowLayout());
        // Give the frame an initial size.
        jfrm.setSize(210, 120);
        // Terminate the program when the user closes the application.
        jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Create empty labels.
        jlabSelected = new JLabel("");
        jlabChanged = new JLabel("");
        // Make check boxes.
        Web = new JCheckBox("Web");
        Desktop = new JCheckBox("Desktop");
        Mobile = new JCheckBox("Mobile");
        // Events generated by the check boxes
        // are handled in common by the itemStateChanged()
        // method implemented by CBDemo.
        Web.addItemListener(this);
        Desktop.addItemListener(this);
        Mobile.addItemListener(this);
        // Add check boxes and labels to the content pane.

        jfrm.add(Web);
        jfrm.add(Desktop);
        jfrm.add(Mobile);
        jfrm.add(jlabChanged);
        jfrm.add(jlabSelected);
        // Display the frame.
        jfrm.setVisible(true);
    }

    // This is the handler for the check boxes.
    public void itemStateChanged(ItemEvent ie) {
        String str = "";
        // Obtain a reference to the check box that
        // caused the event.
        JCheckBox cb = (JCheckBox) ie.getItem();
        // Report what check box changed.
        if(cb.isSelected()) {
            jlabChanged.setText("Clicked: " + cb.getText() + " ");
        } else {
            jlabChanged.setText(cb.getText());
        }
        // Report all selected boxes.
        if(Web.isSelected()) {
            str += "Web ";
        }
        if(Desktop.isSelected()) {
            str += "Desktop";
        }
        if(Mobile.isSelected()) {
            str += "Mobile";
        }
        jlabSelected.setText("" + str);
    }

    public static void main(String args[]) {
        // Create the frame on the event dispatching thread.
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new CBDemo();
            }
        });
    }
}